### ISSUE TITLE
Sparx Enterprise Architect parsing XMI - more detailed instructions

### ISSUE THREAD

**Issue by Jannis1994** [Semprini/pyMDG#39]
Hello, it would be great, if you can explain on a quick tutorial site, which commands needs to be used e.g. for Enterprise Architect XMI Export and what yml is doing what and example commands like this one:

C:\Users\Jannis\Downloads\pyMDG-master\pyMDG-master>python mdg-tool.py generate ./sample_recipes/sparx/config-sparx-python.yaml

The YML then contains data about the test.xmi etc.

**Comment by Semprini** [comment]
Fair call thanks. I will add a tutorial for EA to https://pymdg.readthedocs.io/en/latest/index.html

**Comment by Jannis1994** [comment]
Thanks Semprini, great work so far 👍 
I want to parse my EA Sparx XMI File with your script and do a compliance check based on the created Metadata while parsing.
A JSON Export option of the Metadata (model_package) would be cool, so I can build my Compliance Check based on that output file. But I think I should be able to do this on my own. But it would be a cool Addon for your great parser and an universal interface to use. Currently it looks like, that I have to do some adaptions because I cant see all attributes, text boxes from my EA project in the Model_Package.
Thanks for providing your script for everyone.

**Comment by Semprini** [comment]
No worries, try: 
``mdg-tool dumps <your recipie path>``
which will spit out JSON and may be what you're after. Something else I need to document!

**Comment by Jannis1994** [comment]
The problem with mdg-tool dumps inside the uml\__init__.py function is, that obj_to_dict is losing much  information while parsing to JSON Format. For isntance I only get the ID back but not the name and other details

**Comment by Semprini** [comment]
Hmm, the idea with obj_to_dict is to output all declared attributes and owned objects. If I run `python -m mdg.tools.mdg_tool dumps .\sample_recipes\sparx\config-sparx-django.yaml` I see all attributes of the metamodel dumped. What do you have that's missing? Could you post some more info?

**Comment by Jannis1994** [comment]
If Im using your tutorial.xmi file together with schemagen.yaml it looks okay, but if I use my more complex xmi file it stops parsing all attributes and owned objects.
So for instance I have the following yaml file:
root_package: Application
model_package: Application
source: Path to XMI file
parser: sparx
I start the script with dumps path_to_yaml_file

Then I have the problem, that some information are missing that are in the model_package but not in the output json package.
Is there a config parameter in the yaml file I have to put in, or are the ones I mentioned before okay?

Maybe the fault is on my side, because I created a new uml type called UML_Component and I only get back the EAID instead of attributes like the name and so on. Maybe the meta class or UML Component class is the problem:

> class UMLComponent:

    package: UMLPackage
    attributes: List[UMLAttribute]
    stereotype: Optional[str]
    name: str
    id: Union[int, str]
    documentation: str
    status: Optional[UMLStatuses]
    associations_from: List[UMLAssociation]
    associations_to: List[UMLAssociation]
    classification: Optional[UMLClass]

    class Meta:
        id_field = 'id'
        owned_subobjects: List = ['attributes', ]

    def __init__(self, package: UMLPackage, name: str, id: Union[int, str]) -> None:
        self.attributes = []
        self.associations_from = []
        self.associations_to = []
        self.package = package
        self.stereotype = None
        self.name = name
        self.id = id
        self.documentation = ""
        self.status = None
        self.classification_id: Union[None, int, str] = None

    def __str__(self) -> str:
        return f"{self.name}"`


Do you see here, why it is not parse correctly with obj_to_dict?

**Comment by Semprini** [comment]
I've only used it for data modelling so far but I've grabbed your UMLComponent class. Can you also post your component parse function and I'll have a look what's going on. If you fork the repo and add a sample package with components to the sample.eapx which  replicates the issue.

**Comment by Jannis1994** [comment]
Thanks for helping me, I found the error. Forgot to add components to class Meta inside UMLPackage class for owned_subobjects.
Do you plan to support Components? Our project is using components pretty much.
We have a structure like the following:
Project Root 
- Package Main
--Sub Packages
--- Applications (Package)
---- Application 1 (Package)
----- Component - Application Overview (Stored in XMI diagrams part and linked to Application Package - type is component)
----- Package with type Application inside and type class

MetaModel with High Level Software Architecture

**Comment by Semprini** [comment]
No worries, it would be awesome if you could submit a pull request with your UMLComponent parse function. I've added your UMLComponent model from above. I'd like to add templates to generate infrastructure as code from component views - things like Terraform definitions. My current clients just need data modelling so it's on the back burner.

**Comment by Jannis1994** [comment]
Okay, currently I'm working on it (dependencies and attributes, taggedValues), I will let you know once I have a stable version for components.
