### ISSUE TITLE
Circular reference inside model_package after parsing

### ISSUE THREAD

**Issue by Jannis1994** [Semprini/pyMDG#40]
Hello,
the root_package inside the model_package is not a deep copy. 
So its causing a circular reference (I can open it over and over again).
Is this wanted by you?
I checked the model_package content during debugging inside the /generate/__init__.py file

**Comment by Semprini** [comment]
The root_package should be the parent of the model_package. The way I usually structure the project is:
```
Model (Sparx default package)
    root_package (I name this for the data domain E.g. Customer)
        model_package (I name this 'Data Model')
            sub domain (Optional but large domains like customer I have sub domains like Location where I put address objects)
                <My classes>
        test_package (I name this 'Tests')
            test_case
                <My instances>
```
The in my recipie:
root_package: Customer
model_package: Data Model
test_package: Tests
